### ISSUE TITLE
Vista Nuevo Cliente

### ISSUE THREAD

**Issue by anassa** [anassa/aleph_frontend#17]
Al hacer clic en Cancelar, pone en blanco toda la pantalla y luego aparece la vista sin el menú lateral (previamente estaba), borrando los campos que estaban cargados. 
El comportamiento del botón debe coincidir con la Vista Nuevo Artículo, en donde al hacer clic solamente borra los campos y no pone en blanco toda la pantalla.

**Comment by diegomartin010** [comment]
se soluciono este error en el commit bf2fb02e4792448b397cdafab7bbd4173a89d856
