### ISSUE TITLE
Nueva venta: no trae datos del cliente

### ISSUE THREAD

**Issue by anassa** [anassa/aleph_frontend#26]
Al definir un dni de cliente (existente en la bd), no me trae nombre ni etiquetas

**Comment by nguidi** [comment]
Posiblemente esto ocurra debido a la indexacion que se le agregaron a los clientes. Borra los elementos de la colección clientes y volve a probar. Si anda despues de eso cerra el issue.

**Comment by anassa** [comment]
se solucionó eliminando la colección.
