### ISSUE TITLE
Nueva venta: campo Interés

### ISSUE THREAD

**Issue by anassa** [anassa/aleph_frontend#30]
Debe ser igual al campo Descuento

**Comment by nguidi** [comment]
El valor del campo interes tiene que ser igual que al del campo descuento? Esto ocurre cuando es tarjeta de credito y debito? ambos casos? cual es el sentido de conservar descuento en este caso?

**Comment by anassa** [comment]
Me expresé mal, a con "igual" me refiero a apariencia ![image](https://cloud.githubusercontent.com/assets/4991886/21206950/f3ddb396-c243-11e6-9d33-7ae1f262bc20.png)
El campo descuento, se definió como un campo que siempre debe estar presente en la venta. Es necesario que siempre esté visible.
El campo interés sólo aparece con las formas de pago: t. crédito y t. débito

**Comment by nguidi** [comment]
En el esquema original estaba puesto como seleccionable, lo paso a texto entonces?
