### ISSUE TITLE
Centrar todos los campos

### ISSUE THREAD

**Issue by anassa** [anassa/aleph_frontend#4]
Centrar todos los campos y los botones de Cancelar y Guardar acomodarlos en el lateral inferior izquierdo. 
![nuevo cliente](https://cloud.githubusercontent.com/assets/4991886/20633556/a5bdbe4e-b326-11e6-8821-242f8b4fa668.png)

**Comment by diegomartin010** [comment]
Solucionado. Quedo asi....

![captura](https://cloud.githubusercontent.com/assets/9575268/20642514/9dda8666-b3ef-11e6-8927-4146cce42b87.PNG)

**Comment by anassa** [comment]
Ok!
