### ISSUE TITLE
Los campos Cuenta y Límite de cuenta tienen que estar sin edición

### ISSUE THREAD

**Issue by anassa** [anassa/aleph_frontend#5]
Estos campos se pueden editar con la opción de "on of" que debe estar al lado del label Cuenta.
Por defecto la opción debe estar en off. Cuando se cambia a On solamente permite editar el campo Límite de cuenta y, cuando se presiona el botón Guardar, se guardan todos los cambios y se genera el número de cuenta para el cliente. 
Tener en cuenta el funcionamiento de la vista Nuevo Proveedor.

**Comment by diegomartin010** [comment]
bf2fb02e4792448b397cdafab7bbd4173a89d856 se resolvio de forma similar a la pantalla de
Compras/nuevo_proveedor
