### ISSUE TITLE
Registro Clientes: hay columnas de que se deben quitar

### ISSUE THREAD

**Issue by anassa** [anassa/aleph_frontend#7]
Las únicas columnas que deben quedar en esta vista son: Nombre, Apellido, DNI, Cuenta, Etiquetas, Acciones.

**Comment by diegomartin010** [comment]
Eliminados los campos no necesarios.

Con "etiquetas" todavia voy a ver una cuestion con neri .

... pero va a estar proximamente en cines ...

**Comment by anassa** [comment]
jajajja ok

**Comment by anassa** [comment]
Diego lo volví a abrir al issue porque la vista de Registros Cliente se siguen viendo columnas que no van.

**Comment by diegomartin010** [comment]
Eliminadas columnas innecesarias en commit bf2fb02e4792448b397cdafab7bbd4173a89d856
