### ISSUE TITLE
Falta control sobre los DNI

### ISSUE THREAD

**Issue by anassa** [anassa/aleph_frontend#8]
Cuando se está registrando un cliente se debe controlar el campo DNI para saber si existe otro cliente con el mismo número de DNI. Si existe se debe mostrar un mensaje que informe al usuario, por ejemplo: "Ya existe un cliente con el mismo número de DNI".
No se debe registrar clientes con el mismo número de DNI

**Comment by diegomartin010** [comment]
(en teoria) resuelto.
